# -*- coding: utf-8 -*-
"""Transfomracion de datos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DRc9h4AnjSpOoifAU-dEWSEUM6JZhSOt
"""

import pandas as pd

#importar datos de archivos csv
groups_df = pd.read_csv("STUDENT_GROUP.csv")
groups_df.head()

attendance_df = pd.read_csv("attendance.csv")
attendance_df.head()

groups_df.dtypes

attendance_df.dtypes

attendance_df['STUDENT_ID'] = pd.to_numeric(attendance_df['STUDENT_ID'], errors='coerce')
attendance_df.dtypes

merged_df = pd.merge(groups_df, attendance_df, left_on='student_id', right_on='STUDENT_ID', how='inner')
merged_df.head()

utc_timezone = pytz.utc
local_timezone = pytz.timezone('America/Mexico_City')

merged_df['DTTM'] = pd.to_datetime(merged_df['DTTM']).dt.tz_localize(utc_timezone)
merged_df['DTTM'] = merged_df['DTTM'].dt.tz_convert(local_timezone)

display(merged_df.head())

merged_df['date'] = merged_df['DTTM'].dt.date

attendance_counts = merged_df.groupby(['group_id', 'date']).size().reset_index(name='attendance_count')

min_attendance_per_group = attendance_counts.loc[attendance_counts.groupby('group_id')['attendance_count'].idxmin()]

most_absent_days_per_group = min_attendance_per_group
display(most_absent_days_per_group)

print("Días con más ausencias por grupo:")
display(most_absent_days_per_group)
print("\nExplicación de las columnas:")
print("'group_id': Identificador del grupo de estudiantes.")
print("'date': El día con menor asistencia para ese grupo.")
print("'attendance_count': El número de estudiantes presentes el día con menor asistencia para ese grupo.")